//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tursunt
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel_issue_log
    {
        public int issue_id { get; set; }
        public int fuel_type_id { get; set; }
        public int equipment_id { get; set; }
        public int cluster_id { get; set; }
        public decimal quantity { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public int employee_id { get; set; }
    
        public virtual clusters clusters { get; set; }
        public virtual employees employees { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual fuel_types fuel_types { get; set; }
    }
}
