//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tursunt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class НастяEntities : DbContext
    {
        public НастяEntities()
            : base("name=НастяEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clusters> clusters { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<fuel_issue_log> fuel_issue_log { get; set; }
        public virtual DbSet<fuel_receipts> fuel_receipts { get; set; }
        public virtual DbSet<fuel_types> fuel_types { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
